Bonmin: Bonmin::GuessHeuristic Class Reference
Bonmin::GuessHeuristic Class Reference
#include <BonGuessHeuristic.hpp>
Public Member Functions
GuessHeuristic (CbcModel &model)
Usefull constructor.
GuessHeuristic (const GuessHeuristic &copy)
Copy constructor.
virtual int solution (double &solutionValue, double *betterSolution)
heuristic method providing guess, based on pseudo costs
virtual int solution (double &solutionValue, double *betterSolution, OsiCuts &cs)
virtual CbcHeuristic * clone () const
virtual void resetModel (CbcModel *)
Private Member Functions
GuessHeuristic ()
Default constructor.
GuessHeuristic & operator= (const GuessHeuristic &rhs)
Assignment operator.
Detailed Description
Definition at line 16 of file BonGuessHeuristic.hpp.
Constructor & Destructor Documentation
Bonmin::GuessHeuristic::GuessHeuristic (CbcModel & model)
Usefull constructor.
Bonmin::GuessHeuristic::GuessHeuristic (const GuessHeuristic & copy) [inline]
Copy constructor.
Definition at line 22 of file BonGuessHeuristic.hpp.
Bonmin::GuessHeuristic::GuessHeuristic () [private]
Default constructor.
Referenced by clone().
Member Function Documentation
virtual int Bonmin::GuessHeuristic::solution (double & solutionValue, double * betterSolution) [virtual]
heuristic method providing guess, based on pseudo costs
Referenced by solution().
virtual int Bonmin::GuessHeuristic::solution (double & solutionValue, double * betterSolution, OsiCuts & cs) [inline, virtual]
Definition at line 28 of file BonGuessHeuristic.hpp.
References solution().
virtual CbcHeuristic* Bonmin::GuessHeuristic::clone () const [inline, virtual]
Definition at line 32 of file BonGuessHeuristic.hpp.
References GuessHeuristic().
virtual void Bonmin::GuessHeuristic::resetModel (CbcModel *) [inline, virtual]
Definition at line 36 of file BonGuessHeuristic.hpp.
GuessHeuristic& Bonmin::GuessHeuristic::operator= (const GuessHeuristic & rhs) [private]
Assignment operator.
The documentation for this class was generated from the following file:
BonGuessHeuristic.hpp