Bonmin: Bonmin::RegisteredOptions Class Reference
Bonmin::RegisteredOptions Class Reference
Class to add a few more information to Ipopt::RegisteredOptions.
#include <BonRegisteredOptions.hpp>
Public Types
enum ExtraOptInfosBits {
validInHybrid = 0, validInQG, validInOA, validInBBB,
validInEcp, validIniFP, validInCbc
}
enum ExtraCategoriesInfo {
BonminCategory = 0, IpoptCategory, FilterCategory, BqpdCategory,
CouenneCategory, UndocumentedCategory
}
Public Member Functions
RegisteredOptions ()
Standard constructor.
~RegisteredOptions ()
Standard destructor.
void SetRegisteringCategory (const std::string &registering_category, const ExtraCategoriesInfo extra)
Set registering category with extra information.
void optionExists (const std::string &option)
throw if option does not exists.
void setOptionExtraInfo (const std::string &option, int code)
Set extra information for option.
void optionValidForHybrid (const std::string &option)
Set that option is valid for hybrid.
void optionValidForBQG (const std::string &option)
Set that option is valid for QuesadaGrossmann.
void optionValidForBOA (const std::string &option)
Set that option is valid for Outer approximation.
void optionValidForBBB (const std::string &option)
Set that option is valid for pure branch-and-bound.
void optionValidForBEcp (const std::string &option)
Set that option is valid for B-Ecp.
void optionValidForBiFP (const std::string &option)
Set that option is valid for B-iFP.
void optionValidForCbc (const std::string &option)
Set that option is valid for Cbc.
bool isValidForHybrid (const std::string &option)
Say if option is valid for hybrid.
bool isValidForBQG (const std::string &option)
Say if option is valid for QuesadaGrossmann.
bool isValidForBOA (const std::string &option)
Say if option is valid for Outer approximation.
bool isValidForBBB (const std::string &option)
Say if option is valid for pure branch-and-bound.
bool isValidForBEcp (const std::string &option)
Say if option is valid for B-Ecp.
bool isValidForBiFP (const std::string &option)
Say if option is valid for B-iFP.
bool isValidForCbc (const std::string &option)
Say if option is valid for Cbc.
void writeLatexOptionsTable (std::ostream &of, ExtraCategoriesInfo which)
Output Latex table of options.
void writeHtmlOptionsTable (std::ostream &of, ExtraCategoriesInfo which)
Output html table of options.
void writeLatexHtmlDoc (std::ostream &of, ExtraCategoriesInfo which)
Output Latex/Html ooptions documentation.
void writeBonminOpt (std::ostream &os, ExtraCategoriesInfo which)
Ouptut a bonmin.opt file with options default values and short descriptions.
ExtraCategoriesInfo categoriesInfo (const std::string &s)
Get info about what a category is taking care of (e.g., Ipopt, Bonmin, FilterSQP,...) .
void fillAmplOptionList (ExtraCategoriesInfo which, Ipopt::AmplOptionsList *amplOptList)
Private Member Functions
void chooseOptions (ExtraCategoriesInfo which, std::list< Ipopt::RegisteredOption * > &options)
Output Latex table of options.
void writeHtmlOptionsTable (std::ostream &os, std::list< Ipopt::RegisteredOption * > &options)
Output html table of options.
Private Attributes
std::map< std::string, int > bonOptInfos_
Store extra Informations on Bonmin options.
std::map< std::string,
ExtraCategoriesInfo > categoriesInfos_
Store extra Informations on Registering categories (is bonmin, filterSqp...).
Detailed Description
Class to add a few more information to Ipopt::RegisteredOptions.
In particular, it allows to store code to indicate in which algorithm option is available. It also allows to table summing up all the options both in LaTex and html.
Definition at line 30 of file BonRegisteredOptions.hpp.
Member Enumeration Documentation
enum Bonmin::RegisteredOptions::ExtraOptInfosBits
Enumerator:
validInHybrid
validInQG
Say that option is valid in Quesada Grossmann method (2).
validInOA
Say that option is valid in outer approximation dec (4).
validInBBB
Say that option is valid in the pure branch-and-bound (8).
validInEcp
Say that option is valid in the Ecp (16).
validIniFP
Say that option is valid in the iFP (32).
validInCbc
Say that option is valid when using Cbc_Par (64).
Definition at line 32 of file BonRegisteredOptions.hpp.
enum Bonmin::RegisteredOptions::ExtraCategoriesInfo
Enumerator:
BonminCategory
IpoptCategory
Option category for Ipopt.
FilterCategory
Option category for FilterSqp.
BqpdCategory
Option category for Bqpd.
CouenneCategory
Option category for Couenne.
UndocumentedCategory
For undocumented options.
Definition at line 52 of file BonRegisteredOptions.hpp.
Constructor & Destructor Documentation
Bonmin::RegisteredOptions::RegisteredOptions () [inline]
Standard constructor.
Definition at line 61 of file BonRegisteredOptions.hpp.
Bonmin::RegisteredOptions::~RegisteredOptions () [inline]
Standard destructor.
Definition at line 66 of file BonRegisteredOptions.hpp.
Member Function Documentation
void Bonmin::RegisteredOptions::SetRegisteringCategory (const std::string & registering_category, const ExtraCategoriesInfo extra) [inline]
Set registering category with extra information.
Definition at line 71 of file BonRegisteredOptions.hpp.
References categoriesInfos_.
void Bonmin::RegisteredOptions::optionExists (const std::string & option) [inline]
throw if option does not exists.
Definition at line 77 of file BonRegisteredOptions.hpp.
Referenced by isValidForBBB(), isValidForBEcp(), isValidForBiFP(), isValidForBOA(), isValidForBQG(), isValidForCbc(), isValidForHybrid(), optionValidForBBB(), optionValidForBEcp(), optionValidForBiFP(), optionValidForBOA(), optionValidForBQG(), optionValidForCbc(), optionValidForHybrid(), and setOptionExtraInfo().
void Bonmin::RegisteredOptions::setOptionExtraInfo (const std::string & option, int code) [inline]
Set extra information for option.
Definition at line 86 of file BonRegisteredOptions.hpp.
References bonOptInfos_, and optionExists().
void Bonmin::RegisteredOptions::optionValidForHybrid (const std::string & option) [inline]
Set that option is valid for hybrid.
Definition at line 92 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInHybrid.
void Bonmin::RegisteredOptions::optionValidForBQG (const std::string & option) [inline]
Set that option is valid for QuesadaGrossmann.
Definition at line 97 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInQG.
void Bonmin::RegisteredOptions::optionValidForBOA (const std::string & option) [inline]
Set that option is valid for Outer approximation.
Definition at line 102 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInOA.
void Bonmin::RegisteredOptions::optionValidForBBB (const std::string & option) [inline]
Set that option is valid for pure branch-and-bound.
Definition at line 107 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInBBB.
void Bonmin::RegisteredOptions::optionValidForBEcp (const std::string & option) [inline]
Set that option is valid for B-Ecp.
Definition at line 112 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInEcp.
void Bonmin::RegisteredOptions::optionValidForBiFP (const std::string & option) [inline]
Set that option is valid for B-iFP.
Definition at line 117 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validIniFP.
void Bonmin::RegisteredOptions::optionValidForCbc (const std::string & option) [inline]
Set that option is valid for Cbc.
Definition at line 122 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInCbc.
bool Bonmin::RegisteredOptions::isValidForHybrid (const std::string & option) [inline]
Say if option is valid for hybrid.
Definition at line 128 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInHybrid.
bool Bonmin::RegisteredOptions::isValidForBQG (const std::string & option) [inline]
Say if option is valid for QuesadaGrossmann.
Definition at line 136 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInQG.
bool Bonmin::RegisteredOptions::isValidForBOA (const std::string & option) [inline]
Say if option is valid for Outer approximation.
Definition at line 144 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInOA.
bool Bonmin::RegisteredOptions::isValidForBBB (const std::string & option) [inline]
Say if option is valid for pure branch-and-bound.
Definition at line 152 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInBBB.
bool Bonmin::RegisteredOptions::isValidForBEcp (const std::string & option) [inline]
Say if option is valid for B-Ecp.
Definition at line 161 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInEcp.
bool Bonmin::RegisteredOptions::isValidForBiFP (const std::string & option) [inline]
Say if option is valid for B-iFP.
Definition at line 170 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validIniFP.
bool Bonmin::RegisteredOptions::isValidForCbc (const std::string & option) [inline]
Say if option is valid for Cbc.
Definition at line 179 of file BonRegisteredOptions.hpp.
References bonOptInfos_, optionExists(), and validInCbc.
void Bonmin::RegisteredOptions::writeLatexOptionsTable (std::ostream & of, ExtraCategoriesInfo which)
Output Latex table of options.
void Bonmin::RegisteredOptions::writeHtmlOptionsTable (std::ostream & of, ExtraCategoriesInfo which)
Output html table of options.
void Bonmin::RegisteredOptions::writeLatexHtmlDoc (std::ostream & of, ExtraCategoriesInfo which)
Output Latex/Html ooptions documentation.
void Bonmin::RegisteredOptions::writeBonminOpt (std::ostream & os, ExtraCategoriesInfo which)
Ouptut a bonmin.opt file with options default values and short descriptions.
ExtraCategoriesInfo Bonmin::RegisteredOptions::categoriesInfo (const std::string & s) [inline]
Get info about what a category is taking care of (e.g., Ipopt, Bonmin, FilterSQP,...) .
Definition at line 200 of file BonRegisteredOptions.hpp.
References categoriesInfos_, and IpoptCategory.
void Bonmin::RegisteredOptions::fillAmplOptionList (ExtraCategoriesInfo which, Ipopt::AmplOptionsList * amplOptList)
void Bonmin::RegisteredOptions::chooseOptions (ExtraCategoriesInfo which, std::list< Ipopt::RegisteredOption * > & options) [private]
Output Latex table of options.
void Bonmin::RegisteredOptions::writeHtmlOptionsTable (std::ostream & os, std::list< Ipopt::RegisteredOption * > & options) [private]
Output html table of options.
Member Data Documentation
std::map<std::string, int> Bonmin::RegisteredOptions::bonOptInfos_ [private]
Store extra Informations on Bonmin options.
Definition at line 217 of file BonRegisteredOptions.hpp.
Referenced by isValidForBBB(), isValidForBEcp(), isValidForBiFP(), isValidForBOA(), isValidForBQG(), isValidForCbc(), isValidForHybrid(), optionValidForBBB(), optionValidForBEcp(), optionValidForBiFP(), optionValidForBOA(), optionValidForBQG(), optionValidForCbc(), optionValidForHybrid(), and setOptionExtraInfo().
std::map<std::string, ExtraCategoriesInfo> Bonmin::RegisteredOptions::categoriesInfos_ [private]
Store extra Informations on Registering categories (is bonmin, filterSqp...).
Definition at line 220 of file BonRegisteredOptions.hpp.
Referenced by categoriesInfo(), and SetRegisteringCategory().
The documentation for this class was generated from the following file:
BonRegisteredOptions.hpp