Bonmin: Bonmin::MinlpFeasPump Class Reference
Bonmin::MinlpFeasPump Class Reference
#include <BonFpForMinlp.hpp>
Public Member Functions
MinlpFeasPump (BabSetupBase &b)
Constructor with basic setup.
MinlpFeasPump (const MinlpFeasPump &copy)
Copy constructor.
~MinlpFeasPump ()
Destructor.
void setStrategy (const CbcStrategy &strategy)
virtual CglCutGenerator * clone () const
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register OA options.
Protected Member Functions
virtual double performOa (OsiCuts &cs, solverManip &lpManip, BabInfo *babInfo, double &cutoff, const CglTreeInfo &info) const
virtual method which performs the OA algorithm by modifying lp and nlp.
virtual bool doLocalSearch (BabInfo *babInfo) const
virutal method to decide if local search is performed
void set_fp_objective (OsiSolverInterface &si, const double *colsol) const
Put objective of MIP according to FP scheme.
Private Attributes
SubMipSolver * subMip_
int passBound_
Wether or not to pass bound to master algorithm.
Detailed Description
Definition at line 15 of file BonFpForMinlp.hpp.
Constructor & Destructor Documentation
Bonmin::MinlpFeasPump::MinlpFeasPump (BabSetupBase & b)
Constructor with basic setup.
Referenced by clone().
Bonmin::MinlpFeasPump::MinlpFeasPump (const MinlpFeasPump & copy) [inline]
Copy constructor.
Definition at line 21 of file BonFpForMinlp.hpp.
Bonmin::MinlpFeasPump::~MinlpFeasPump ()
Destructor.
Member Function Documentation
void Bonmin::MinlpFeasPump::setStrategy (const CbcStrategy & strategy) [inline]
Definition at line 30 of file BonFpForMinlp.hpp.
References Bonmin::OaDecompositionBase::parameters_, and Bonmin::OaDecompositionBase::Parameters::setStrategy().
virtual CglCutGenerator* Bonmin::MinlpFeasPump::clone () const [inline, virtual]
Definition at line 35 of file BonFpForMinlp.hpp.
References MinlpFeasPump().
static void Bonmin::MinlpFeasPump::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register OA options.
virtual double Bonmin::MinlpFeasPump::performOa (OsiCuts & cs, solverManip & lpManip, BabInfo * babInfo, double & cutoff, const CglTreeInfo & info) const [protected, virtual]
virtual method which performs the OA algorithm by modifying lp and nlp.
Implements Bonmin::OaDecompositionBase.
virtual bool Bonmin::MinlpFeasPump::doLocalSearch (BabInfo * babInfo) const [protected, virtual]
virutal method to decide if local search is performed
Implements Bonmin::OaDecompositionBase.
void Bonmin::MinlpFeasPump::set_fp_objective (OsiSolverInterface & si, const double * colsol) const [protected]
Put objective of MIP according to FP scheme.
Member Data Documentation
SubMipSolver* Bonmin::MinlpFeasPump::subMip_ [private]
Definition at line 52 of file BonFpForMinlp.hpp.
int Bonmin::MinlpFeasPump::passBound_ [private]
Wether or not to pass bound to master algorithm.
Definition at line 54 of file BonFpForMinlp.hpp.
The documentation for this class was generated from the following file:
BonFpForMinlp.hpp