Bonmin: Bonmin::HeuristicDiveVectorLength Class Reference
Bonmin::HeuristicDiveVectorLength Class Reference
#include <BonHeuristicDiveVectorLength.hpp>
Public Member Functions
HeuristicDiveVectorLength ()
Default Constructor.
HeuristicDiveVectorLength (BonminSetup *setup)
Constructor with setup.
HeuristicDiveVectorLength (const HeuristicDiveVectorLength &copy)
Copy constructor.
~HeuristicDiveVectorLength ()
Destructor.
HeuristicDiveVectorLength & operator= (const HeuristicDiveVectorLength &rhs)
Assignment operator.
virtual CbcHeuristic * clone () const
Clone.
virtual void setSetup (BonminSetup *setup)
Change setup used for heuristic.
virtual void setInternalVariables (TMINLP2TNLP *minlp)
sets internal variables
virtual void selectVariableToBranch (TMINLP2TNLP *minlp, const vector< int > &integerColumns, const double *newSolution, int &bestColumn, int &bestRound)
Selects the next variable to branch on.
void Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register the options common to all local search based heuristics.
Private Attributes
int * columnLength_
the number of nonzero elements in each column
Detailed Description
Definition at line 21 of file BonHeuristicDiveVectorLength.hpp.
Constructor & Destructor Documentation
Bonmin::HeuristicDiveVectorLength::HeuristicDiveVectorLength ()
Default Constructor.
Bonmin::HeuristicDiveVectorLength::HeuristicDiveVectorLength (BonminSetup * setup)
Constructor with setup.
Bonmin::HeuristicDiveVectorLength::HeuristicDiveVectorLength (const HeuristicDiveVectorLength & copy)
Copy constructor.
Bonmin::HeuristicDiveVectorLength::~HeuristicDiveVectorLength () [inline]
Destructor.
Definition at line 33 of file BonHeuristicDiveVectorLength.hpp.
References columnLength_.
Member Function Documentation
HeuristicDiveVectorLength& Bonmin::HeuristicDiveVectorLength::operator= (const HeuristicDiveVectorLength & rhs)
Assignment operator.
virtual CbcHeuristic* Bonmin::HeuristicDiveVectorLength::clone () const [virtual]
Clone.
Implements Bonmin::HeuristicDive.
virtual void Bonmin::HeuristicDiveVectorLength::setSetup (BonminSetup * setup) [inline, virtual]
Change setup used for heuristic.
Reimplemented from Bonmin::HeuristicDive.
Definition at line 45 of file BonHeuristicDiveVectorLength.hpp.
References Initialize(), and Bonmin::BabSetupBase::options().
virtual void Bonmin::HeuristicDiveVectorLength::setInternalVariables (TMINLP2TNLP * minlp) [virtual]
sets internal variables
Implements Bonmin::HeuristicDive.
virtual void Bonmin::HeuristicDiveVectorLength::selectVariableToBranch (TMINLP2TNLP * minlp, const vector< int > & integerColumns, const double * newSolution, int & bestColumn, int & bestRound) [virtual]
Selects the next variable to branch on.
If bestColumn = -1, it means that no variable was found
Implements Bonmin::HeuristicDive.
static void Bonmin::HeuristicDiveVectorLength::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register the options common to all local search based heuristics.
void Bonmin::HeuristicDiveVectorLength::Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Referenced by setSetup().
Member Data Documentation
int* Bonmin::HeuristicDiveVectorLength::columnLength_ [private]
the number of nonzero elements in each column
Definition at line 70 of file BonHeuristicDiveVectorLength.hpp.
Referenced by ~HeuristicDiveVectorLength().
The documentation for this class was generated from the following file:
BonHeuristicDiveVectorLength.hpp