Bonmin: Bonmin::BonminSetup Class Reference
Bonmin::BonminSetup Class Reference
#include <BonBonminSetup.hpp>
Public Member Functions
BonminSetup (const CoinMessageHandler *handler=NULL)
Default constructor.
BonminSetup (const BonminSetup &other)
Copy constructor.
BonminSetup (const BonminSetup &setup, OsiTMINLPInterface &nlp)
Copy but uses an other nlp.
BonminSetup (const BonminSetup &setup, OsiTMINLPInterface &nlp, const std::string &prefix)
Copy but uses another nlp and algorithm.
virtual BabSetupBase * clone () const
virtual copy constructor.
BonminSetup * clone (OsiTMINLPInterface &nlp) const
BonminSetup * clone (OsiTMINLPInterface &nlp, const std::string &prefix) const
Make a copy but take options with different prefix.
virtual ~BonminSetup ()
void initialize (Ipopt::SmartPtr< TMINLP > tminlp, bool createContinuousSolver=true)
Initialize, read options and create appropriate bonmin setup.
void initialize (const OsiTMINLPInterface &nlpSi, bool createContinuousSolver=true)
Initialize, read options and create appropriate bonmin setup.
Bonmin::Algorithm getAlgorithm ()
Get the algorithm used.
void addCutGenerator (CuttingMethod &cg)
Methods to instantiate: Registering and retrieving options and initializing everything.
virtual void registerOptions ()
Register all the options for this algorithm instance.
virtual void setBabDefaultOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Setup the defaults options for this algorithm.
Static Public Member Functions
static void registerAllOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register all bonmin type executable options.
Protected Member Functions
void addMilpCutGenerators ()
Add milp cut generators according to options.
void initializeBBB ()
Initialize a plain branch-and-bound.
void initializeBHyb (bool createContinuousSolver=false)
Initialize a branch-and-cut with some OA.
Static Protected Member Functions
static void registerMilpCutGenerators (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register standard MILP cut generators.
Private Attributes
Algorithm algo_
Detailed Description
Definition at line 25 of file BonBonminSetup.hpp.
Constructor & Destructor Documentation
Bonmin::BonminSetup::BonminSetup (const CoinMessageHandler * handler = NULL)
Default constructor.
Referenced by clone().
Bonmin::BonminSetup::BonminSetup (const BonminSetup & other)
Copy constructor.
Bonmin::BonminSetup::BonminSetup (const BonminSetup & setup, OsiTMINLPInterface & nlp)
Copy but uses an other nlp.
Bonmin::BonminSetup::BonminSetup (const BonminSetup & setup, OsiTMINLPInterface & nlp, const std::string & prefix)
Copy but uses another nlp and algorithm.
virtual Bonmin::BonminSetup::~BonminSetup () [inline, virtual]
Definition at line 58 of file BonBonminSetup.hpp.
Member Function Documentation
virtual BabSetupBase* Bonmin::BonminSetup::clone () const [inline, virtual]
virtual copy constructor.
Implements Bonmin::BabSetupBase.
Definition at line 42 of file BonBonminSetup.hpp.
References BonminSetup().
BonminSetup* Bonmin::BonminSetup::clone (OsiTMINLPInterface & nlp) const [inline, virtual]
Make a copy with solver replace by one passed .
Reimplemented from Bonmin::BabSetupBase.
Definition at line 51 of file BonBonminSetup.hpp.
References BonminSetup().
BonminSetup* Bonmin::BonminSetup::clone (OsiTMINLPInterface & nlp, const std::string & prefix) const [inline]
Make a copy but take options with different prefix.
Definition at line 55 of file BonBonminSetup.hpp.
References BonminSetup().
virtual void Bonmin::BonminSetup::registerOptions () [virtual]
Register all the options for this algorithm instance.
Reimplemented from Bonmin::BabSetupBase.
virtual void Bonmin::BonminSetup::setBabDefaultOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [inline, virtual]
Setup the defaults options for this algorithm.
Reimplemented from Bonmin::BabSetupBase.
Definition at line 65 of file BonBonminSetup.hpp.
static void Bonmin::BonminSetup::registerAllOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register all bonmin type executable options.
Reimplemented from Bonmin::BabSetupBase.
void Bonmin::BonminSetup::initialize (Ipopt::SmartPtr< TMINLP > tminlp, bool createContinuousSolver = true)
Initialize, read options and create appropriate bonmin setup.
Referenced by main().
void Bonmin::BonminSetup::initialize (const OsiTMINLPInterface & nlpSi, bool createContinuousSolver = true)
Initialize, read options and create appropriate bonmin setup.
Bonmin::Algorithm Bonmin::BonminSetup::getAlgorithm ()
Get the algorithm used.
void Bonmin::BonminSetup::addCutGenerator (CuttingMethod & cg) [inline]
Reimplemented from Bonmin::BabSetupBase.
Definition at line 77 of file BonBonminSetup.hpp.
static void Bonmin::BonminSetup::registerMilpCutGenerators (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static, protected]
Register standard MILP cut generators.
void Bonmin::BonminSetup::addMilpCutGenerators () [protected]
Add milp cut generators according to options.
void Bonmin::BonminSetup::initializeBBB () [protected]
Initialize a plain branch-and-bound.
void Bonmin::BonminSetup::initializeBHyb (bool createContinuousSolver = false) [protected]
Initialize a branch-and-cut with some OA.
Member Data Documentation
Algorithm Bonmin::BonminSetup::algo_ [private]
Definition at line 90 of file BonBonminSetup.hpp.
The documentation for this class was generated from the following file:
BonBonminSetup.hpp