Bonmin: Bonmin::OsiTMINLPInterface Class Reference
Bonmin::OsiTMINLPInterface Class Reference
This is class provides an Osi interface for a Mixed Integer Linear Program expressed as a TMINLP (so that we can use it for example as the continuous solver in Cbc).
#include <BonOsiTMINLPInterface.hpp>
Classes
class Messages
Messages written by an OsiTMINLPInterface.
class SimpleError
Error class to throw exceptions from OsiTMINLPInterface.
Public Types
enum WarmStartModes { None, FakeBasis, Optimum, InteriorPoint }
enum MessagesTypes {
SOLUTION_FOUND, INFEASIBLE_SOLUTION_FOUND, UNSOLVED_PROBLEM_FOUND, WARNING_RESOLVING,
WARN_SUCCESS_WS, WARN_SUCCESS_RANDOM, WARN_CONTINUING_ON_FAILURE, SUSPECT_PROBLEM,
SUSPECT_PROBLEM2, IPOPT_SUMMARY, BETTER_SOL, LOG_HEAD,
LOG_FIRST_LINE, LOG_LINE, ALTERNATE_OBJECTIVE, WARN_RESOLVE_BEFORE_INITIAL_SOLVE,
ERROR_NO_TNLPSOLVER, WARNING_NON_CONVEX_OA, SOLVER_DISAGREE_STATUS, SOLVER_DISAGREE_VALUE,
OSITMINLPINTERFACE_DUMMY_END
}
Type of the messages specifically written by OsiTMINLPInterface.
Public Member Functions
TNLPSolver::UnsolvedError * newUnsolvedError (int num, Ipopt::SmartPtr< TMINLP2TNLP > problem, std::string name)
void setNumIterationSuspect (int value)
const TMINLP2TNLP * problem () const
get pointer to the TMINLP2TNLP adapter
TMINLP2TNLP * problem ()
const TMINLP * model () const
Bonmin::TMINLP * model ()
const Bonmin::TNLPSolver * solver () const
const std::list
< Ipopt::SmartPtr< TNLPSolver > > & debug_apps () const
TNLPSolver * solver ()
Constructors and destructors
OsiTMINLPInterface ()
Default Constructor.
void initialize (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions, Ipopt::SmartPtr< Ipopt::OptionsList > options, Ipopt::SmartPtr< Ipopt::Journalist > journalist, const std::string &prefix, Ipopt::SmartPtr< TMINLP > tminlp)
Facilitator to initialize interface.
void initialize (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions, Ipopt::SmartPtr< Ipopt::OptionsList > options, Ipopt::SmartPtr< Ipopt::Journalist > journalist, Ipopt::SmartPtr< TMINLP > tminlp)
Facilitator to initialize interface.
void setModel (Ipopt::SmartPtr< TMINLP > tminlp)
Set the model to be solved by interface.
void setSolver (Ipopt::SmartPtr< TNLPSolver > app)
Set the solver to be used by interface.
void use (Ipopt::SmartPtr< TMINLP2TNLP > tminlp2tnlp)
Sets the TMINLP2TNLP to be used by the interface.
OsiTMINLPInterface (const OsiTMINLPInterface &)
Copy constructor.
OsiSolverInterface * clone (bool copyData=true) const
Virtual copy constructor.
OsiTMINLPInterface & operator= (const OsiTMINLPInterface &rhs)
Assignment operator.
virtual ~OsiTMINLPInterface ()
Destructor.
void readOptionFile (const std::string &fileName)
Read parameter file.
const Ipopt::SmartPtr
< Ipopt::OptionsList > options () const
Retrieve OsiTMINLPApplication option list.
Ipopt::SmartPtr
< Ipopt::OptionsList > options ()
Retrieve OsiTMINLPApplication option list.
const char * prefix () const
Default Constructor.
Solve methods
virtual void initialSolve ()
Solve initial continuous relaxation.
virtual void initialSolve (const char *whereFrom)
Solve initial continuous relaxation (precising from where)
virtual void resolve ()
Resolve the continuous relaxation after problem modification.
virtual void resolve (const char *whereFrom)
Resolve the continuous relaxation after problem modification.
virtual void resolveForCost (int numretry, bool keepWs)
Resolve the problem with different random starting points to try to find a better solution (only makes sense for a non-convex problem.
virtual void resolveForRobustness (int numretry)
Method to be called when a problem has failed to be solved.
virtual void branchAndBound ()
Nescessary for compatibility with OsiSolverInterface but does nothing.
Methods returning info on how the solution process terminated
virtual bool isAbandoned () const
Are there a numerical difficulties?
virtual bool isProvenOptimal () const
Is optimality proven?
virtual bool isProvenPrimalInfeasible () const
Is primal infeasiblity proven?
virtual bool isProvenDualInfeasible () const
Is dual infeasiblity proven?
virtual bool isPrimalObjectiveLimitReached () const
Is the given primal objective limit reached?
virtual bool isDualObjectiveLimitReached () const
Is the given dual objective limit reached?
virtual bool isIterationLimitReached () const
Iteration limit reached?
void continuingOnAFailure ()
Warn solver that branch-and-bound is continuing after a failure.
double getNewCutoffDecr ()
Are there a numerical difficulties?
void setNewCutoffDecr (double d)
Are there a numerical difficulties?
bool hasContinuedOnAFailure ()
Did we continue on a failure.
void ignoreFailures ()
tell to ignore the failures (don't throw, don't fathom, don't report)
void forceInfeasible ()
Force current solution to be infeasible.
void forceBranchable ()
Force current solution to be branched on (make it fractionnal with small objective)
Parameter set/get methods
The set methods return true if the parameter was set to the given value, false otherwise.
There can be various reasons for failure: the given parameter is not applicable for the solver (e.g., refactorization frequency for the clp algorithm), the parameter is not yet implemented for the solver or simply the value of the parameter is out of the range the solver accepts. If a parameter setting call returns false check the details of your solver.
The get methods return true if the given parameter is applicable for the solver and is implemented. In this case the value of the parameter is returned in the second argument. Otherwise they return false.
bool setIntParam (OsiIntParam key, int value)
bool setDblParam (OsiDblParam key, double value)
bool setStrParam (OsiStrParam key, const std::string &value)
bool getIntParam (OsiIntParam key, int &value) const
bool getDblParam (OsiDblParam key, double &value) const
bool getStrParam (OsiStrParam key, std::string &value) const
double getPushFact () const
Problem information methods
These methods call the solver's query routines to return information about the problem referred to by the current object.
Querying a problem that has no data associated with it result in zeros for the number of rows and columns, and NULL pointers from the methods that return vectors.
Const pointers returned from any data-query method are valid as long as the data is unchanged and the solver is not called.
virtual int getNumCols () const
Get number of columns.
virtual int getNumRows () const
Get number of rows.
const
OsiSolverInterface::OsiNameVec & getVarNames ()
get name of variables
virtual const double * getColLower () const
Get pointer to array[getNumCols()] of column lower bounds.
virtual const double * getColUpper () const
Get pointer to array[getNumCols()] of column upper bounds.
virtual const char * getRowSense () const
Get pointer to array[getNumRows()] of row constraint senses.
virtual const double * getRightHandSide () const
Get pointer to array[getNumRows()] of rows right-hand sides.
virtual const double * getRowRange () const
Get pointer to array[getNumRows()] of row ranges.
virtual const double * getRowLower () const
Get pointer to array[getNumRows()] of row lower bounds.
virtual const double * getRowUpper () const
Get pointer to array[getNumRows()] of row upper bounds.
virtual double getObjSense () const
Get objective function sense (1 for min (default), -1 for max) Always minimizes.
virtual bool isContinuous (int colNumber) const
Return true if column is continuous.
virtual bool isBinary (int columnNumber) const
Return true if column is binary.
virtual bool isInteger (int columnNumber) const
Return true if column is integer.
virtual bool isIntegerNonBinary (int columnNumber) const
Return true if column is general integer.
virtual bool isFreeBinary (int columnNumber) const
Return true if column is binary and not fixed at either bound.
virtual double getInfinity () const
Get solver's value for infinity.
const int * getPriorities () const
Get priorities on integer variables.
const int * getBranchingDirections () const
get prefered branching directions
const double * getUpPsCosts () const
Get number of columns.
const double * getDownPsCosts () const
Get number of columns.
Methods related to querying the solution
virtual const double * getColSolution () const
Get pointer to array[getNumCols()] of primal solution vector.
virtual const double * getRowPrice () const
Get pointer to array[getNumRows()] of dual prices.
virtual const double * getReducedCost () const
Get a pointer to array[getNumCols()] of reduced costs.
virtual const double * getRowActivity () const
Get pointer to array[getNumRows()] of row activity levels (constraint matrix times the solution vector.
virtual int getIterationCount () const
Get how many iterations it took to solve the problem (whatever "iteration" mean to the solver.
int nCallOptimizeTNLP ()
get total number of calls to solve.
double totalNlpSolveTime ()
get total time taken to solve NLP's.
int totalIterations ()
get total number of iterations
Methods to modify the objective, bounds, and solution
virtual void setColLower (int elementIndex, double elementValue)
Set a single column lower bound.
virtual void setColUpper (int elementIndex, double elementValue)
Set a single column upper bound.
virtual void setColLower (const double *array)
Set the lower bounds for all columns array [getNumCols()] is an array of values for the objective.
virtual void setColUpper (const double *array)
Set the upper bounds for all columns array [getNumCols()] is an array of values for the objective.
virtual void setRowLower (int elementIndex, double elementValue)
Set a single row lower bound.
virtual void setRowUpper (int elementIndex, double elementValue)
Set a single row upper bound.
virtual void setRowType (int index, char sense, double rightHandSide, double range)
Set the type of a single row.
virtual void setObjSense (double s)
Set the objective function sense (disabled).
virtual void setColSolution (const double *colsol)
Set the primal solution variable values Set the values for the starting point.
virtual void setRowPrice (const double *rowprice)
Set dual solution variable values.
WarmStart related methods (those should really do nothing for the moment)
virtual CoinWarmStart * getEmptyWarmStart () const
Get an empty warm start object.
virtual CoinWarmStart * getWarmStart () const
Get warmstarting information.
virtual bool setWarmStart (const CoinWarmStart *warmstart)
Set warmstarting information.
void setWarmStartMode (int mode)
Get an empty warm start object.
WarmStartModes getWarmStartMode ()
Get an empty warm start object.
void randomStartingPoint ()
Get an empty warm start object.
virtual bool basisIsAvailable () const
Get an empty warm start object.
Methods to set variable type
virtual void setContinuous (int index)
Set the index-th variable to be a continuous variable.
virtual void setInteger (int index)
Set the index-th variable to be an integer variable.
Dummy functions
Functions which have to be implemented in an OsiSolverInterface, but which do not do anything (but throwing exceptions) here in the case of a minlp solved using an nlp solver for continuous relaxations
virtual int getNumElements () const
Cbc will understand that no matrix exsits if return -1.
virtual const double * getObjCoefficients () const
This returns the objective function gradient at the current point.
virtual const CoinPackedMatrix * getMatrixByRow () const
We have to keep this but it will return NULL.
virtual const CoinPackedMatrix * getMatrixByCol () const
We have to keep this but it will return NULL.
virtual void setObjCoeff (int elementIndex, double elementValue)
We have to keep this but it will throw an error.
virtual void addCol (const CoinPackedVectorBase &vec, const double collb, const double colub, const double obj)
We have to keep this but it will throw an error.
virtual void deleteCols (const int num, const int *colIndices)
We have to keep this but it will throw an error.
virtual void addRow (const CoinPackedVectorBase &vec, const double rowlb, const double rowub)
We have to keep this but it will throw an error.
virtual void addRow (const CoinPackedVectorBase &vec, const char rowsen, const double rowrhs, const double rowrng)
We have to keep this but it will throw an error.
virtual void deleteRows (const int num, const int *rowIndices)
We have to keep this but it will throw an error.
virtual void loadProblem (const CoinPackedMatrix &matrix, const double *collb, const double *colub, const double *obj, const double *rowlb, const double *rowub)
We have to keep this but it will throw an error.
virtual void assignProblem (CoinPackedMatrix *&matrix, double *&collb, double *&colub, double *&obj, double *&rowlb, double *&rowub)
We have to keep this but it will throw an error.
virtual void loadProblem (const CoinPackedMatrix &matrix, const double *collb, const double *colub, const double *obj, const char *rowsen, const double *rowrhs, const double *rowrng)
We have to keep this but it will throw an error.
virtual void assignProblem (CoinPackedMatrix *&matrix, double *&collb, double *&colub, double *&obj, char *&rowsen, double *&rowrhs, double *&rowrng)
We have to keep this but it will throw an error.
virtual void loadProblem (const int numcols, const int numrows, const int *start, const int *index, const double *value, const double *collb, const double *colub, const double *obj, const double *rowlb, const double *rowub)
We have to keep this but it will throw an error.
virtual void loadProblem (const int numcols, const int numrows, const int *start, const int *index, const double *value, const double *collb, const double *colub, const double *obj, const char *rowsen, const double *rowrhs, const double *rowrng)
We have to keep this but it will throw an error.
virtual int readMps (const char *filename, const char *extension="mps")
We have to keep this but it will throw an error.
virtual void writeMps (const char *filename, const char *extension="mps", double objSense=0.0) const
We have to keep this but it will throw an error.
virtual std::vector< double * > getDualRays (int maxNumRays, bool fullRay=false) const
Throws an error.
virtual std::vector< double * > getPrimalRays (int maxNumRays) const
Throws an error.
Control of Ipopt output
void setSolverOutputToDefault ()
void forceSolverOutput (int log_level)
Sets and Getss
virtual double getObjValue () const
Get objective function value (can't use default)
Methods to build outer approximations
virtual void extractLinearRelaxation (OsiSolverInterface &si, const double *x, bool getObj=1)
Extract a linear relaxation of the MINLP.
virtual void addObjectiveFunction (OsiSolverInterface &si, const double *x)
Add constraint corresponding to objective function.
virtual void extractLinearRelaxation (OsiSolverInterface &si, bool getObj=1, bool solveNlp=1)
Extract a linear relaxation of the MINLP.
void getOuterApproximation (OsiCuts &cs, int getObj, const double *x2, bool global)
Get the outer approximation constraints at the current optimal point.
void getOuterApproximation (OsiCuts &cs, const double *x, int getObj, const double *x2, bool global)
Get the outer approximation constraints at provided point.
virtual void getOuterApproximation (OsiCuts &cs, const double *x, int getObj, const double *x2, double theta, bool global)
Get the outer approximation constraints at provided point.
virtual void getConstraintOuterApproximation (OsiCuts &cs, int constraintNumber, const double *x, const double *x2, bool global)
Get the outer approximation at provided point for given constraint.
void getConstraintOuterApproximation (OsiCuts &cs, int constraintNumber, const double *x2, bool global)
Get the outer approximation at current optimal point for given constraint.
void getBendersCut (OsiCuts &cs, bool global)
Get a benders cut from solution.
double solveFeasibilityProblem (size_t n, const double *x_bar, const int *ind, double a, double s, int L)
Given a point x_bar this solves the problem of finding the point which minimize a convex combination between the distance to x_bar and the original objective function f(x): .
Friends
class BonminParam
Detailed Description
This is class provides an Osi interface for a Mixed Integer Linear Program expressed as a TMINLP (so that we can use it for example as the continuous solver in Cbc).
Definition at line 48 of file BonOsiTMINLPInterface.hpp.
Member Enumeration Documentation
enum Bonmin::OsiTMINLPInterface::WarmStartModes
Enumerator:
None
FakeBasis
Optimum
InteriorPoint
Definition at line 87 of file BonOsiTMINLPInterface.hpp.
enum Bonmin::OsiTMINLPInterface::MessagesTypes
Type of the messages specifically written by OsiTMINLPInterface.
Enumerator:
SOLUTION_FOUND
found a feasible solution
INFEASIBLE_SOLUTION_FOUND
found an infeasible problem
UNSOLVED_PROBLEM_FOUND
found an unsolved problem
WARNING_RESOLVING
Warn that a problem is resolved.
WARN_SUCCESS_WS
Problem not solved with warm start but solved without.
WARN_SUCCESS_RANDOM
Subproblem not solve with warm start but solved with random point.
WARN_CONTINUING_ON_FAILURE
a failure occured but is continuing
SUSPECT_PROBLEM
Output the number of the problem.
SUSPECT_PROBLEM2
Output the number of the problem.
IPOPT_SUMMARY
Output summary statistics on Ipopt solution.
BETTER_SOL
Found a better solution with random values.
LOG_HEAD
Head of "civilized" log.
LOG_FIRST_LINE
First line (first solve) of log.
LOG_LINE
standard line (retry solving) of log.
ALTERNATE_OBJECTIVE
Recomputed integer feasible with alternate objective function.
WARN_RESOLVE_BEFORE_INITIAL_SOLVE
resolve() has been called but there was no previous call to initialSolve().
ERROR_NO_TNLPSOLVER
Trying to access non-existent TNLPSolver.
WARNING_NON_CONVEX_OA
Warn that there are equality or ranged constraints and OA may works bad.
SOLVER_DISAGREE_STATUS
Different solver gives different status for problem.
SOLVER_DISAGREE_VALUE
Different solver gives different optimal value for problem.
OSITMINLPINTERFACE_DUMMY_END
Definition at line 94 of file BonOsiTMINLPInterface.hpp.
Constructor & Destructor Documentation
Bonmin::OsiTMINLPInterface::OsiTMINLPInterface ()
Default Constructor.
Bonmin::OsiTMINLPInterface::OsiTMINLPInterface (const OsiTMINLPInterface &)
Copy constructor.
virtual Bonmin::OsiTMINLPInterface::~OsiTMINLPInterface () [virtual]
Destructor.
Member Function Documentation
TNLPSolver::UnsolvedError* Bonmin::OsiTMINLPInterface::newUnsolvedError (int num, Ipopt::SmartPtr< TMINLP2TNLP > problem, std::string name) [inline]
Definition at line 82 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::initialize (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions, Ipopt::SmartPtr< Ipopt::OptionsList > options, Ipopt::SmartPtr< Ipopt::Journalist > journalist, const std::string & prefix, Ipopt::SmartPtr< TMINLP > tminlp)
Facilitator to initialize interface.
Referenced by initialize().
void Bonmin::OsiTMINLPInterface::initialize (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions, Ipopt::SmartPtr< Ipopt::OptionsList > options, Ipopt::SmartPtr< Ipopt::Journalist > journalist, Ipopt::SmartPtr< TMINLP > tminlp) [inline]
Facilitator to initialize interface.
Definition at line 148 of file BonOsiTMINLPInterface.hpp.
References initialize().
void Bonmin::OsiTMINLPInterface::setModel (Ipopt::SmartPtr< TMINLP > tminlp)
Set the model to be solved by interface.
void Bonmin::OsiTMINLPInterface::setSolver (Ipopt::SmartPtr< TNLPSolver > app)
Set the solver to be used by interface.
void Bonmin::OsiTMINLPInterface::use (Ipopt::SmartPtr< TMINLP2TNLP > tminlp2tnlp)
Sets the TMINLP2TNLP to be used by the interface.
OsiSolverInterface* Bonmin::OsiTMINLPInterface::clone (bool copyData = true) const
Virtual copy constructor.
OsiTMINLPInterface& Bonmin::OsiTMINLPInterface::operator= (const OsiTMINLPInterface & rhs)
Assignment operator.
void Bonmin::OsiTMINLPInterface::readOptionFile (const std::string & fileName)
Read parameter file.
const Ipopt::SmartPtr<Ipopt::OptionsList> Bonmin::OsiTMINLPInterface::options () const
Retrieve OsiTMINLPApplication option list.
Ipopt::SmartPtr<Ipopt::OptionsList> Bonmin::OsiTMINLPInterface::options ()
Retrieve OsiTMINLPApplication option list.
const char* Bonmin::OsiTMINLPInterface::prefix () const [inline]
Default Constructor.
Definition at line 183 of file BonOsiTMINLPInterface.hpp.
References ERROR_NO_TNLPSOLVER.
virtual void Bonmin::OsiTMINLPInterface::initialSolve () [virtual]
Solve initial continuous relaxation.
Referenced by extractLinearRelaxation().
virtual void Bonmin::OsiTMINLPInterface::initialSolve (const char * whereFrom) [virtual]
Solve initial continuous relaxation (precising from where)
virtual void Bonmin::OsiTMINLPInterface::resolve () [virtual]
Resolve the continuous relaxation after problem modification.
initialSolve may or may not have been called before this is called. In any case, this must solve the problem, and speed the process up if it can reuse any remnants of data that might exist from a previous solve.
virtual void Bonmin::OsiTMINLPInterface::resolve (const char * whereFrom) [virtual]
Resolve the continuous relaxation after problem modification.
initialSolve may or may not have been called before this is called. In any case, this must solve the problem, and speed the process up if it can reuse any remnants of data that might exist from a previous solve.
virtual void Bonmin::OsiTMINLPInterface::resolveForCost (int numretry, bool keepWs) [virtual]
Resolve the problem with different random starting points to try to find a better solution (only makes sense for a non-convex problem.
virtual void Bonmin::OsiTMINLPInterface::resolveForRobustness (int numretry) [virtual]
Method to be called when a problem has failed to be solved.
Will try to resolve it with different settings.
virtual void Bonmin::OsiTMINLPInterface::branchAndBound () [inline, virtual]
Nescessary for compatibility with OsiSolverInterface but does nothing.
Definition at line 225 of file BonOsiTMINLPInterface.hpp.
virtual bool Bonmin::OsiTMINLPInterface::isAbandoned () const [virtual]
Are there a numerical difficulties?
virtual bool Bonmin::OsiTMINLPInterface::isProvenOptimal () const [virtual]
Is optimality proven?
virtual bool Bonmin::OsiTMINLPInterface::isProvenPrimalInfeasible () const [virtual]
Is primal infeasiblity proven?
virtual bool Bonmin::OsiTMINLPInterface::isProvenDualInfeasible () const [virtual]
Is dual infeasiblity proven?
virtual bool Bonmin::OsiTMINLPInterface::isPrimalObjectiveLimitReached () const [virtual]
Is the given primal objective limit reached?
virtual bool Bonmin::OsiTMINLPInterface::isDualObjectiveLimitReached () const [virtual]
Is the given dual objective limit reached?
virtual bool Bonmin::OsiTMINLPInterface::isIterationLimitReached () const [virtual]
Iteration limit reached?
void Bonmin::OsiTMINLPInterface::continuingOnAFailure () [inline]
Warn solver that branch-and-bound is continuing after a failure.
Definition at line 252 of file BonOsiTMINLPInterface.hpp.
double Bonmin::OsiTMINLPInterface::getNewCutoffDecr () [inline]
Are there a numerical difficulties?
Definition at line 260 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::setNewCutoffDecr (double d) [inline]
Are there a numerical difficulties?
Definition at line 265 of file BonOsiTMINLPInterface.hpp.
bool Bonmin::OsiTMINLPInterface::hasContinuedOnAFailure () [inline]
Did we continue on a failure.
Definition at line 272 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::ignoreFailures () [inline]
tell to ignore the failures (don't throw, don't fathom, don't report)
Definition at line 277 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::forceInfeasible () [inline]
Force current solution to be infeasible.
Definition at line 282 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::forceBranchable () [inline]
Force current solution to be branched on (make it fractionnal with small objective)
Definition at line 287 of file BonOsiTMINLPInterface.hpp.
bool Bonmin::OsiTMINLPInterface::setIntParam (OsiIntParam key, int value)
bool Bonmin::OsiTMINLPInterface::setDblParam (OsiDblParam key, double value)
bool Bonmin::OsiTMINLPInterface::setStrParam (OsiStrParam key, const std::string & value)
bool Bonmin::OsiTMINLPInterface::getIntParam (OsiIntParam key, int & value) const
bool Bonmin::OsiTMINLPInterface::getDblParam (OsiDblParam key, double & value) const
bool Bonmin::OsiTMINLPInterface::getStrParam (OsiStrParam key, std::string & value) const
double Bonmin::OsiTMINLPInterface::getPushFact () const [inline]
Definition at line 325 of file BonOsiTMINLPInterface.hpp.
virtual int Bonmin::OsiTMINLPInterface::getNumCols () const [virtual]
Get number of columns.
virtual int Bonmin::OsiTMINLPInterface::getNumRows () const [virtual]
Get number of rows.
const OsiSolverInterface::OsiNameVec& Bonmin::OsiTMINLPInterface::getVarNames ()
get name of variables
virtual const double* Bonmin::OsiTMINLPInterface::getColLower () const [virtual]
Get pointer to array[getNumCols()] of column lower bounds.
virtual const double* Bonmin::OsiTMINLPInterface::getColUpper () const [virtual]
Get pointer to array[getNumCols()] of column upper bounds.
virtual const char* Bonmin::OsiTMINLPInterface::getRowSense () const [virtual]
Get pointer to array[getNumRows()] of row constraint senses.
'L': <= constraint
'E': = constraint
'G': >= constraint
'R': ranged constraint
'N': free constraint
virtual const double* Bonmin::OsiTMINLPInterface::getRightHandSide () const [virtual]
Get pointer to array[getNumRows()] of rows right-hand sides.
if rowsense()[i] == 'L' then rhs()[i] == rowupper()[i]
if rowsense()[i] == 'G' then rhs()[i] == rowlower()[i]
if rowsense()[i] == 'R' then rhs()[i] == rowupper()[i]
if rowsense()[i] == 'N' then rhs()[i] == 0.0
virtual const double* Bonmin::OsiTMINLPInterface::getRowRange () const [virtual]
Get pointer to array[getNumRows()] of row ranges.
if rowsense()[i] == 'R' then rowrange()[i] == rowupper()[i] - rowlower()[i]
if rowsense()[i] != 'R' then rowrange()[i] is 0.0
virtual const double* Bonmin::OsiTMINLPInterface::getRowLower () const [virtual]
Get pointer to array[getNumRows()] of row lower bounds.
virtual const double* Bonmin::OsiTMINLPInterface::getRowUpper () const [virtual]
Get pointer to array[getNumRows()] of row upper bounds.
virtual double Bonmin::OsiTMINLPInterface::getObjSense () const [inline, virtual]
Get objective function sense (1 for min (default), -1 for max) Always minimizes.
Definition at line 399 of file BonOsiTMINLPInterface.hpp.
virtual bool Bonmin::OsiTMINLPInterface::isContinuous (int colNumber) const [virtual]
Return true if column is continuous.
virtual bool Bonmin::OsiTMINLPInterface::isBinary (int columnNumber) const [virtual]
Return true if column is binary.
virtual bool Bonmin::OsiTMINLPInterface::isInteger (int columnNumber) const [virtual]
Return true if column is integer.
Note: This function returns true if the the column is binary or a general integer.
virtual bool Bonmin::OsiTMINLPInterface::isIntegerNonBinary (int columnNumber) const [virtual]
Return true if column is general integer.
virtual bool Bonmin::OsiTMINLPInterface::isFreeBinary (int columnNumber) const [virtual]
Return true if column is binary and not fixed at either bound.
virtual double Bonmin::OsiTMINLPInterface::getInfinity () const [virtual]
Get solver's value for infinity.
const int* Bonmin::OsiTMINLPInterface::getPriorities () const [inline]
Get priorities on integer variables.
Definition at line 426 of file BonOsiTMINLPInterface.hpp.
References Bonmin::TMINLP::BranchingInfo::priorities.
const int* Bonmin::OsiTMINLPInterface::getBranchingDirections () const [inline]
get prefered branching directions
Definition at line 434 of file BonOsiTMINLPInterface.hpp.
References Bonmin::TMINLP::BranchingInfo::branchingDirections.
const double* Bonmin::OsiTMINLPInterface::getUpPsCosts () const [inline]
Get number of columns.
Definition at line 441 of file BonOsiTMINLPInterface.hpp.
References Bonmin::TMINLP::BranchingInfo::upPsCosts.
const double* Bonmin::OsiTMINLPInterface::getDownPsCosts () const [inline]
Get number of columns.
Definition at line 448 of file BonOsiTMINLPInterface.hpp.
References Bonmin::TMINLP::BranchingInfo::downPsCosts.
virtual const double* Bonmin::OsiTMINLPInterface::getColSolution () const [virtual]
Get pointer to array[getNumCols()] of primal solution vector.
Referenced by extractLinearRelaxation(), getConstraintOuterApproximation(), and getOuterApproximation().
virtual const double* Bonmin::OsiTMINLPInterface::getRowPrice () const [virtual]
Get pointer to array[getNumRows()] of dual prices.
virtual const double* Bonmin::OsiTMINLPInterface::getReducedCost () const [virtual]
Get a pointer to array[getNumCols()] of reduced costs.
virtual const double* Bonmin::OsiTMINLPInterface::getRowActivity () const [virtual]
Get pointer to array[getNumRows()] of row activity levels (constraint matrix times the solution vector.
virtual int Bonmin::OsiTMINLPInterface::getIterationCount () const [virtual]
Get how many iterations it took to solve the problem (whatever "iteration" mean to the solver.
Todo:
Figure out what it could mean for Ipopt.
int Bonmin::OsiTMINLPInterface::nCallOptimizeTNLP () [inline]
get total number of calls to solve.
Definition at line 482 of file BonOsiTMINLPInterface.hpp.
double Bonmin::OsiTMINLPInterface::totalNlpSolveTime () [inline]
get total time taken to solve NLP's.
Definition at line 487 of file BonOsiTMINLPInterface.hpp.
int Bonmin::OsiTMINLPInterface::totalIterations () [inline]
get total number of iterations
Definition at line 492 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::setColLower (int elementIndex, double elementValue) [virtual]
Set a single column lower bound.
Use -getInfinity() for -infinity.
virtual void Bonmin::OsiTMINLPInterface::setColUpper (int elementIndex, double elementValue) [virtual]
Set a single column upper bound.
Use getInfinity() for infinity.
virtual void Bonmin::OsiTMINLPInterface::setColLower (const double * array) [virtual]
Set the lower bounds for all columns array [getNumCols()] is an array of values for the objective.
virtual void Bonmin::OsiTMINLPInterface::setColUpper (const double * array) [virtual]
Set the upper bounds for all columns array [getNumCols()] is an array of values for the objective.
virtual void Bonmin::OsiTMINLPInterface::setRowLower (int elementIndex, double elementValue) [virtual]
Set a single row lower bound.
Use -getInfinity() for -infinity.
virtual void Bonmin::OsiTMINLPInterface::setRowUpper (int elementIndex, double elementValue) [virtual]
Set a single row upper bound.
Use getInfinity() for infinity.
virtual void Bonmin::OsiTMINLPInterface::setRowType (int index, char sense, double rightHandSide, double range) [virtual]
Set the type of a single row.
virtual void Bonmin::OsiTMINLPInterface::setObjSense (double s) [virtual]
Set the objective function sense (disabled).
(1 for min (default), -1 for max)
Todo:
Make it work.
Bug:
Can not treat maximisation problems.
virtual void Bonmin::OsiTMINLPInterface::setColSolution (const double * colsol) [virtual]
Set the primal solution variable values Set the values for the starting point.
Warning:
getColSolution will never return this vector (unless it is optimal).
Referenced by extractLinearRelaxation().
virtual void Bonmin::OsiTMINLPInterface::setRowPrice (const double * rowprice) [virtual]
Set dual solution variable values.
set the values for the starting point.
Warning:
getRowPrice will never return this vector (unless it is optimal).
Referenced by extractLinearRelaxation().
virtual CoinWarmStart* Bonmin::OsiTMINLPInterface::getEmptyWarmStart () const [virtual]
Get an empty warm start object.
This routine returns an empty CoinWarmStartBasis object. Its purpose is to provide a way to give a client a warm start basis object of the appropriate type, which can resized and modified as desired.
virtual CoinWarmStart* Bonmin::OsiTMINLPInterface::getWarmStart () const [virtual]
Get warmstarting information.
virtual bool Bonmin::OsiTMINLPInterface::setWarmStart (const CoinWarmStart * warmstart) [virtual]
Set warmstarting information.
Return true/false depending on whether the warmstart information was accepted or not.
void Bonmin::OsiTMINLPInterface::setWarmStartMode (int mode) [inline]
Get an empty warm start object.
This routine returns an empty CoinWarmStartBasis object. Its purpose is to provide a way to give a client a warm start basis object of the appropriate type, which can resized and modified as desired.
Definition at line 576 of file BonOsiTMINLPInterface.hpp.
WarmStartModes Bonmin::OsiTMINLPInterface::getWarmStartMode () [inline]
Get an empty warm start object.
This routine returns an empty CoinWarmStartBasis object. Its purpose is to provide a way to give a client a warm start basis object of the appropriate type, which can resized and modified as desired.
Definition at line 579 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::randomStartingPoint ()
Get an empty warm start object.
This routine returns an empty CoinWarmStartBasis object. Its purpose is to provide a way to give a client a warm start basis object of the appropriate type, which can resized and modified as desired.
virtual bool Bonmin::OsiTMINLPInterface::basisIsAvailable () const [inline, virtual]
Get an empty warm start object.
This routine returns an empty CoinWarmStartBasis object. Its purpose is to provide a way to give a client a warm start basis object of the appropriate type, which can resized and modified as desired.
Definition at line 586 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::setContinuous (int index) [virtual]
Set the index-th variable to be a continuous variable.
virtual void Bonmin::OsiTMINLPInterface::setInteger (int index) [virtual]
Set the index-th variable to be an integer variable.
void Bonmin::OsiTMINLPInterface::setNumIterationSuspect (int value) [inline]
Definition at line 605 of file BonOsiTMINLPInterface.hpp.
virtual int Bonmin::OsiTMINLPInterface::getNumElements () const [inline, virtual]
Cbc will understand that no matrix exsits if return -1.
Definition at line 618 of file BonOsiTMINLPInterface.hpp.
virtual const double* Bonmin::OsiTMINLPInterface::getObjCoefficients () const [virtual]
This returns the objective function gradient at the current point.
It seems to be required for Cbc's pseudo cost initialization
virtual const CoinPackedMatrix* Bonmin::OsiTMINLPInterface::getMatrixByRow () const [inline, virtual]
We have to keep this but it will return NULL.
Definition at line 632 of file BonOsiTMINLPInterface.hpp.
virtual const CoinPackedMatrix* Bonmin::OsiTMINLPInterface::getMatrixByCol () const [inline, virtual]
We have to keep this but it will return NULL.
Definition at line 640 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::setObjCoeff (int elementIndex, double elementValue) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 647 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::addCol (const CoinPackedVectorBase & vec, const double collb, const double colub, const double obj) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 655 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::deleteCols (const int num, const int * colIndices) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 664 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::addRow (const CoinPackedVectorBase & vec, const double rowlb, const double rowub) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 672 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::addRow (const CoinPackedVectorBase & vec, const char rowsen, const double rowrhs, const double rowrng) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 680 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::deleteRows (const int num, const int * rowIndices) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 689 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::loadProblem (const CoinPackedMatrix & matrix, const double * collb, const double * colub, const double * obj, const double * rowlb, const double * rowub) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 699 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::assignProblem (CoinPackedMatrix *& matrix, double *& collb, double *& colub, double *& obj, double *& rowlb, double *& rowub) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 711 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::loadProblem (const CoinPackedMatrix & matrix, const double * collb, const double * colub, const double * obj, const char * rowsen, const double * rowrhs, const double * rowrng) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 721 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::assignProblem (CoinPackedMatrix *& matrix, double *& collb, double *& colub, double *& obj, char *& rowsen, double *& rowrhs, double *& rowrng) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 733 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::loadProblem (const int numcols, const int numrows, const int * start, const int * index, const double * value, const double * collb, const double * colub, const double * obj, const double * rowlb, const double * rowub) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 745 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::loadProblem (const int numcols, const int numrows, const int * start, const int * index, const double * value, const double * collb, const double * colub, const double * obj, const char * rowsen, const double * rowrhs, const double * rowrng) [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 758 of file BonOsiTMINLPInterface.hpp.
virtual int Bonmin::OsiTMINLPInterface::readMps (const char * filename, const char * extension = "mps") [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 772 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::writeMps (const char * filename, const char * extension = "mps", double objSense = 0.0) const [inline, virtual]
We have to keep this but it will throw an error.
Definition at line 782 of file BonOsiTMINLPInterface.hpp.
virtual std::vector<double*> Bonmin::OsiTMINLPInterface::getDualRays (int maxNumRays, bool fullRay = false) const [inline, virtual]
Throws an error.
Definition at line 791 of file BonOsiTMINLPInterface.hpp.
virtual std::vector<double*> Bonmin::OsiTMINLPInterface::getPrimalRays (int maxNumRays) const [inline, virtual]
Throws an error.
Definition at line 798 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::setSolverOutputToDefault () [inline]
Definition at line 815 of file BonOsiTMINLPInterface.hpp.
void Bonmin::OsiTMINLPInterface::forceSolverOutput (int log_level) [inline]
Definition at line 817 of file BonOsiTMINLPInterface.hpp.
virtual double Bonmin::OsiTMINLPInterface::getObjValue () const [virtual]
Get objective function value (can't use default)
const TMINLP2TNLP* Bonmin::OsiTMINLPInterface::problem () const [inline]
get pointer to the TMINLP2TNLP adapter
Definition at line 829 of file BonOsiTMINLPInterface.hpp.
Referenced by extractLinearRelaxation().
TMINLP2TNLP* Bonmin::OsiTMINLPInterface::problem () [inline]
Definition at line 834 of file BonOsiTMINLPInterface.hpp.
const TMINLP* Bonmin::OsiTMINLPInterface::model () const [inline]
Definition at line 839 of file BonOsiTMINLPInterface.hpp.
Bonmin::TMINLP* Bonmin::OsiTMINLPInterface::model () [inline]
Definition at line 844 of file BonOsiTMINLPInterface.hpp.
const Bonmin::TNLPSolver* Bonmin::OsiTMINLPInterface::solver () const [inline]
Definition at line 849 of file BonOsiTMINLPInterface.hpp.
const std::list<Ipopt::SmartPtr<TNLPSolver> >& Bonmin::OsiTMINLPInterface::debug_apps () const [inline]
Definition at line 854 of file BonOsiTMINLPInterface.hpp.
TNLPSolver* Bonmin::OsiTMINLPInterface::solver () [inline]
Definition at line 858 of file BonOsiTMINLPInterface.hpp.
virtual void Bonmin::OsiTMINLPInterface::extractLinearRelaxation (OsiSolverInterface & si, const double * x, bool getObj = 1) [virtual]
Extract a linear relaxation of the MINLP.
Use user-provided point to build first-order outer-approximation constraints at the optimum. And put it in an OsiSolverInterface.
Referenced by extractLinearRelaxation().
virtual void Bonmin::OsiTMINLPInterface::addObjectiveFunction (OsiSolverInterface & si, const double * x) [virtual]
Add constraint corresponding to objective function.
virtual void Bonmin::OsiTMINLPInterface::extractLinearRelaxation (OsiSolverInterface & si, bool getObj = 1, bool solveNlp = 1) [inline, virtual]
Extract a linear relaxation of the MINLP.
Solve the continuous relaxation and takes first-order outer-approximation constraints at the optimum. The put everything in an OsiSolverInterface.
Definition at line 880 of file BonOsiTMINLPInterface.hpp.
References extractLinearRelaxation(), getColSolution(), initialSolve(), problem(), setColSolution(), and setRowPrice().
void Bonmin::OsiTMINLPInterface::getOuterApproximation (OsiCuts & cs, int getObj, const double * x2, bool global) [inline]
Get the outer approximation constraints at the current optimal point.
If x2 is different from NULL only add cuts violated by x2. (Only get outer-approximations of nonlinear constraints of the problem.)
Definition at line 895 of file BonOsiTMINLPInterface.hpp.
References getColSolution().
Referenced by getOuterApproximation().
void Bonmin::OsiTMINLPInterface::getOuterApproximation (OsiCuts & cs, const double * x, int getObj, const double * x2, bool global) [inline]
Get the outer approximation constraints at provided point.
If x2 is different from NULL only add cuts violated by x2. (Only get outer-approximations of nonlinear constraints of the problem.)
Definition at line 903 of file BonOsiTMINLPInterface.hpp.
References getOuterApproximation().
virtual void Bonmin::OsiTMINLPInterface::getOuterApproximation (OsiCuts & cs, const double * x, int getObj, const double * x2, double theta, bool global) [virtual]
Get the outer approximation constraints at provided point.
If x2 is different from NULL only add cuts violated by x2 by more than delta. (Only get outer-approximations of nonlinear constraints of the problem.)
virtual void Bonmin::OsiTMINLPInterface::getConstraintOuterApproximation (OsiCuts & cs, int constraintNumber, const double * x, const double * x2, bool global) [virtual]
Get the outer approximation at provided point for given constraint.
Referenced by getConstraintOuterApproximation().
void Bonmin::OsiTMINLPInterface::getConstraintOuterApproximation (OsiCuts & cs, int constraintNumber, const double * x2, bool global) [inline]
Get the outer approximation at current optimal point for given constraint.
Definition at line 918 of file BonOsiTMINLPInterface.hpp.
References getColSolution(), and getConstraintOuterApproximation().
void Bonmin::OsiTMINLPInterface::getBendersCut (OsiCuts & cs, bool global)
Get a benders cut from solution.
double Bonmin::OsiTMINLPInterface::solveFeasibilityProblem (size_t n, const double * x_bar, const int * ind, double a, double s, int L)
Given a point x_bar this solves the problem of finding the point which minimize a convex combination between the distance to x_bar and the original objective function f(x): .
Returns:
Distance between feasibility set a x_bar on components in ind
Parameters:
n number of elements in array x_bar and ind
s scaling of the original objective.
a Combination to take between feasibility and original objective (must be between 0 and 1).
L L-norm to use (can be either 1 or 2).
Friends And Related Function Documentation
friend class BonminParam [friend]
Definition at line 50 of file BonOsiTMINLPInterface.hpp.
The documentation for this class was generated from the following file:
BonOsiTMINLPInterface.hpp