Bonmin: Bonmin::DummyHeuristic Class Reference
Bonmin::DummyHeuristic Class Reference
#include <BonDummyHeuristic.hpp>
Public Member Functions
DummyHeuristic (OsiTMINLPInterface *si=NULL)
Default constructor.
DummyHeuristic (CbcModel &model, OsiTMINLPInterface *si=NULL)
Usefull constructor.
DummyHeuristic (const DummyHeuristic &copy)
Copy constructor.
void setNlp (OsiTMINLPInterface *si)
Set nlp_.
virtual int solution (double &solutionValue, double *betterSolution)
heuristic method
virtual int solution (double &solutionValue, double *betterSolution, OsiCuts &cs)
virtual CbcHeuristic * clone () const
virtual void resetModel (CbcModel *)
virtual bool shouldHeurRun (int whereFrom)
Private Attributes
OsiTMINLPInterface * nlp_
Pointer to the Ipopt interface.
bool knowsSolution
Do I have a solution?
Detailed Description
Definition at line 17 of file BonDummyHeuristic.hpp.
Constructor & Destructor Documentation
Bonmin::DummyHeuristic::DummyHeuristic (OsiTMINLPInterface * si = NULL)
Default constructor.
Referenced by clone().
Bonmin::DummyHeuristic::DummyHeuristic (CbcModel & model, OsiTMINLPInterface * si = NULL)
Usefull constructor.
Bonmin::DummyHeuristic::DummyHeuristic (const DummyHeuristic & copy) [inline]
Copy constructor.
Definition at line 25 of file BonDummyHeuristic.hpp.
Member Function Documentation
void Bonmin::DummyHeuristic::setNlp (OsiTMINLPInterface * si)
Set nlp_.
virtual int Bonmin::DummyHeuristic::solution (double & solutionValue, double * betterSolution) [virtual]
heuristic method
Referenced by solution().
virtual int Bonmin::DummyHeuristic::solution (double & solutionValue, double * betterSolution, OsiCuts & cs) [inline, virtual]
Definition at line 34 of file BonDummyHeuristic.hpp.
References solution().
virtual CbcHeuristic* Bonmin::DummyHeuristic::clone () const [inline, virtual]
Definition at line 38 of file BonDummyHeuristic.hpp.
References DummyHeuristic().
virtual void Bonmin::DummyHeuristic::resetModel (CbcModel *) [inline, virtual]
Definition at line 42 of file BonDummyHeuristic.hpp.
virtual bool Bonmin::DummyHeuristic::shouldHeurRun (int whereFrom) [inline, virtual]
Definition at line 44 of file BonDummyHeuristic.hpp.
Member Data Documentation
OsiTMINLPInterface* Bonmin::DummyHeuristic::nlp_ [private]
Pointer to the Ipopt interface.
Definition at line 48 of file BonDummyHeuristic.hpp.
bool Bonmin::DummyHeuristic::knowsSolution [private]
Do I have a solution?
Definition at line 50 of file BonDummyHeuristic.hpp.
The documentation for this class was generated from the following file:
BonDummyHeuristic.hpp