Bonmin: Bonmin::HeuristicFPump Class Reference
Bonmin::HeuristicFPump Class Reference
#include <BonHeuristicFPump.hpp>
Public Member Functions
HeuristicFPump ()
Default constructor.
HeuristicFPump (BonminSetup *setup)
Constructor with setup.
HeuristicFPump (const HeuristicFPump &copy)
Copy constructor.
~HeuristicFPump ()
Destructor.
HeuristicFPump & operator= (const HeuristicFPump &rhs)
Assignment operator.
virtual CbcHeuristic * clone () const
Virtual constructor.
virtual void resetModel (CbcModel *model)
Resets stuff if model changes.
void setSetup (BonminSetup *setup)
Change setup used for heuristic.
virtual int solution (double &solutionValue, double *betterSolution)
Performs heuristic.
virtual int solution (double &solutionValue, double *betterSolution, OsiCuts &cs)
Performs heuristic with add cust.
void Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register the options for this heuristic.
Private Attributes
BonminSetup * setup_
Setup to use for local searches (will make copies).
int objective_norm_
Norm of the objective function - either 1 or 2.
int enableAdvanced_
To enable advanced unstable stuff.
Detailed Description
Definition at line 18 of file BonHeuristicFPump.hpp.
Constructor & Destructor Documentation
Bonmin::HeuristicFPump::HeuristicFPump ()
Default constructor.
Referenced by clone().
Bonmin::HeuristicFPump::HeuristicFPump (BonminSetup * setup)
Constructor with setup.
Bonmin::HeuristicFPump::HeuristicFPump (const HeuristicFPump & copy)
Copy constructor.
Bonmin::HeuristicFPump::~HeuristicFPump () [inline]
Destructor.
Definition at line 31 of file BonHeuristicFPump.hpp.
Member Function Documentation
HeuristicFPump& Bonmin::HeuristicFPump::operator= (const HeuristicFPump & rhs)
Assignment operator.
virtual CbcHeuristic* Bonmin::HeuristicFPump::clone () const [inline, virtual]
Virtual constructor.
Definition at line 37 of file BonHeuristicFPump.hpp.
References HeuristicFPump().
virtual void Bonmin::HeuristicFPump::resetModel (CbcModel * model) [inline, virtual]
Resets stuff if model changes.
Definition at line 42 of file BonHeuristicFPump.hpp.
void Bonmin::HeuristicFPump::setSetup (BonminSetup * setup) [inline]
Change setup used for heuristic.
Definition at line 47 of file BonHeuristicFPump.hpp.
References Initialize(), Bonmin::BabSetupBase::options(), and setup_.
virtual int Bonmin::HeuristicFPump::solution (double & solutionValue, double * betterSolution) [virtual]
Performs heuristic.
Referenced by solution().
virtual int Bonmin::HeuristicFPump::solution (double & solutionValue, double * betterSolution, OsiCuts & cs) [inline, virtual]
Performs heuristic with add cust.
Definition at line 56 of file BonHeuristicFPump.hpp.
References solution().
static void Bonmin::HeuristicFPump::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register the options for this heuristic.
void Bonmin::HeuristicFPump::Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Referenced by setSetup().
Member Data Documentation
BonminSetup* Bonmin::HeuristicFPump::setup_ [private]
Setup to use for local searches (will make copies).
Definition at line 69 of file BonHeuristicFPump.hpp.
Referenced by setSetup().
int Bonmin::HeuristicFPump::objective_norm_ [private]
Norm of the objective function - either 1 or 2.
Definition at line 72 of file BonHeuristicFPump.hpp.
int Bonmin::HeuristicFPump::enableAdvanced_ [private]
To enable advanced unstable stuff.
Definition at line 75 of file BonHeuristicFPump.hpp.
The documentation for this class was generated from the following file:
BonHeuristicFPump.hpp