Bonmin: Bonmin::OACutGenerator2 Class Reference
Bonmin::OACutGenerator2 Class Reference
Class to perform OA in its classical form.
#include <BonOACutGenerator2.hpp>
Public Member Functions
OACutGenerator2 (BabSetupBase &b)
Constructor with basic setup.
OACutGenerator2 (const OACutGenerator2 &copy)
Copy constructor.
~OACutGenerator2 ()
Destructor.
void setStrategy (const CbcStrategy &strategy)
virtual CglCutGenerator * clone () const
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register OA options.
Protected Member Functions
virtual double performOa (OsiCuts &cs, solverManip &lpManip, BabInfo *babInfo, double &cutoff, const CglTreeInfo &info) const
virtual method which performs the OA algorithm by modifying lp and nlp.
virtual bool doLocalSearch (BabInfo *babInfo) const
virutal method to decide if local search is performed
Private Attributes
SubMipSolver * subMip_
Detailed Description
Class to perform OA in its classical form.
Definition at line 18 of file BonOACutGenerator2.hpp.
Constructor & Destructor Documentation
Bonmin::OACutGenerator2::OACutGenerator2 (BabSetupBase & b)
Constructor with basic setup.
Referenced by clone().
Bonmin::OACutGenerator2::OACutGenerator2 (const OACutGenerator2 & copy) [inline]
Copy constructor.
Definition at line 25 of file BonOACutGenerator2.hpp.
Bonmin::OACutGenerator2::~OACutGenerator2 ()
Destructor.
Member Function Documentation
void Bonmin::OACutGenerator2::setStrategy (const CbcStrategy & strategy) [inline]
Definition at line 33 of file BonOACutGenerator2.hpp.
References Bonmin::OaDecompositionBase::parameters_, and Bonmin::OaDecompositionBase::Parameters::setStrategy().
virtual CglCutGenerator* Bonmin::OACutGenerator2::clone () const [inline, virtual]
Definition at line 38 of file BonOACutGenerator2.hpp.
References OACutGenerator2().
static void Bonmin::OACutGenerator2::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register OA options.
virtual double Bonmin::OACutGenerator2::performOa (OsiCuts & cs, solverManip & lpManip, BabInfo * babInfo, double & cutoff, const CglTreeInfo & info) const [protected, virtual]
virtual method which performs the OA algorithm by modifying lp and nlp.
Implements Bonmin::OaDecompositionBase.
virtual bool Bonmin::OACutGenerator2::doLocalSearch (BabInfo * babInfo) const [protected, virtual]
virutal method to decide if local search is performed
Implements Bonmin::OaDecompositionBase.
Member Data Documentation
SubMipSolver* Bonmin::OACutGenerator2::subMip_ [private]
Definition at line 53 of file BonOACutGenerator2.hpp.
The documentation for this class was generated from the following file:
BonOACutGenerator2.hpp