Bonmin: Bonmin::HeuristicDiveMIPFractional Class Reference
Bonmin::HeuristicDiveMIPFractional Class Reference
#include <BonHeuristicDiveMIPFractional.hpp>
Public Member Functions
HeuristicDiveMIPFractional ()
Default Constructor.
HeuristicDiveMIPFractional (BonminSetup *setup)
Constructor with setup.
HeuristicDiveMIPFractional (const HeuristicDiveMIPFractional &copy)
Copy constructor.
~HeuristicDiveMIPFractional ()
Destructor.
HeuristicDiveMIPFractional & operator= (const HeuristicDiveMIPFractional &rhs)
Assignment operator.
virtual CbcHeuristic * clone () const
Clone.
virtual void setSetup (BonminSetup *setup)
Change setup used for heuristic.
virtual void setInternalVariables (TMINLP2TNLP *minlp)
sets internal variables
virtual void selectVariableToBranch (TMINLP2TNLP *minlp, const vector< int > &integerColumns, const double *newSolution, int &bestColumn, int &bestRound)
Selects the next variable to branch on.
void Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register the options common to all local search based heuristics.
Detailed Description
Definition at line 21 of file BonHeuristicDiveMIPFractional.hpp.
Constructor & Destructor Documentation
Bonmin::HeuristicDiveMIPFractional::HeuristicDiveMIPFractional ()
Default Constructor.
Bonmin::HeuristicDiveMIPFractional::HeuristicDiveMIPFractional (BonminSetup * setup)
Constructor with setup.
Bonmin::HeuristicDiveMIPFractional::HeuristicDiveMIPFractional (const HeuristicDiveMIPFractional & copy)
Copy constructor.
Bonmin::HeuristicDiveMIPFractional::~HeuristicDiveMIPFractional () [inline]
Destructor.
Definition at line 33 of file BonHeuristicDiveMIPFractional.hpp.
Member Function Documentation
HeuristicDiveMIPFractional& Bonmin::HeuristicDiveMIPFractional::operator= (const HeuristicDiveMIPFractional & rhs)
Assignment operator.
virtual CbcHeuristic* Bonmin::HeuristicDiveMIPFractional::clone () const [virtual]
Clone.
Implements Bonmin::HeuristicDiveMIP.
virtual void Bonmin::HeuristicDiveMIPFractional::setSetup (BonminSetup * setup) [inline, virtual]
Change setup used for heuristic.
Reimplemented from Bonmin::HeuristicDiveMIP.
Definition at line 42 of file BonHeuristicDiveMIPFractional.hpp.
References Initialize(), and Bonmin::BabSetupBase::options().
virtual void Bonmin::HeuristicDiveMIPFractional::setInternalVariables (TMINLP2TNLP * minlp) [virtual]
sets internal variables
Implements Bonmin::HeuristicDiveMIP.
virtual void Bonmin::HeuristicDiveMIPFractional::selectVariableToBranch (TMINLP2TNLP * minlp, const vector< int > & integerColumns, const double * newSolution, int & bestColumn, int & bestRound) [virtual]
Selects the next variable to branch on.
If bestColumn = -1, it means that no variable was found
Implements Bonmin::HeuristicDiveMIP.
static void Bonmin::HeuristicDiveMIPFractional::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register the options common to all local search based heuristics.
void Bonmin::HeuristicDiveMIPFractional::Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Referenced by setSetup().
The documentation for this class was generated from the following file:
BonHeuristicDiveMIPFractional.hpp